# Airbnb NYC Dataset - Data Cleaning

## Project Objective

This notebook applies the data cleaning plan developed during the Data Understanding & Assessment phase. Missing values, incorrect data types, invalid records, and data quality issues are addressed to prepare the dataset for exploratory data analysis.

## Cleaning Strategy

| Column | Issue                                    | Cleaning Strategy                                                                 | Reason                                                                                                                           |
| ------ | ---------------------------------------- | --------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------- |
| `name` | 16 missing values, 4 numeric-only titles | Replaced missing values with **"No Listing Title"**; retained numeric-only titles | Preserved all records without introducing fabricated listing names. Numeric-only titles could not be confidently corrected. |
| `host_name` | 21 missing values, numeric-only names | Replaced missing values with **"No Host Name"**; retained numeric-only names | Preserved all records without introducing fabricated host names. Numeric-only values could not be reliably corrected. |
| `neighbourhood_group` | Stored as object | Converted to category | Contains a small, fixed set of repeated values. Using the category data type reduces memory usage and accurately represents the categorical nature of the data. |
| `neighbourhood` | Stored as object | Converted to category | Contains a finite set of repeated neighbourhood names. Converting to category reduces memory usage, improves performance, and accurately represents the categorical nature of the data. |
| `room_type` | Stored as object | Converted to category | Contains only three repeated categories. Converting to category reduces memory usage, improves performance, and accurately represents the categorical nature of the data. |
| `last_review`	| Stored as object; expected missing values	| Converted to datetime; retained NaT values |	Missing values correctly indicate listings with no reviews. Converting to datetime enables date-based analysis while preserving data integrity. |
| `price`	| 11 zero-priced listings	| Removed zero-priced listings; retained genuine high-priced listings	| Zero-priced listings likely represent invalid or missing pricing information. Since they account for only 0.02% of the dataset and the correct prices could not be recovered, removing them improves the reliability of price-based analyses while having a negligible impact on the dataset. |
| `minimum_nights` | Statistical upper outliers | Retained all values | The outliers represent legitimate long-term rental policies rather than data quality issues. No evidence was found to justify removing or modifying these records.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/AB_NYC_2019.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [ ]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [ ]:
df.sample(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
42512,32992225,Enchanting quiet NOLITA sanctuary loft,28480501,Elisha,Manhattan,Nolita,40.72222,-73.99692,Private room,150,14,3,2019-06-21,2.57,1,36
14951,11890279,"Beautiful Flatiron 3 Bedroom, 2 Bath Loft",63407204,C,Manhattan,Flatiron District,40.73987,-73.98982,Entire home/apt,650,5,42,2019-05-24,1.07,1,335
3439,2062630,Large 1 bedroom apartment (shared),6313448,Lexy,Bronx,Bronxdale,40.85667,-73.86543,Entire home/apt,80,1,1,2014-08-19,0.02,1,0
8518,6555586,A 2BR Oasis in Red Hook,34285520,Penny,Brooklyn,Red Hook,40.67811,-74.00606,Entire home/apt,145,7,2,2015-09-01,0.04,1,0
1714,775326,Cozy Room in Artistic Brownstone,1568517,Karl & Catherine,Queens,Long Island City,40.74527,-73.94629,Private room,69,1,153,2019-01-18,1.89,2,132

## 1. Cleaning the `name` Column

In [ ]:
df['name'] = df['name'].fillna('No Listing Title')

In [ ]:
df[df['name']=='No Listing Title'].shape[0]

16

In [ ]:
df['name'].isnull().sum()

np.int64(0)

## 2. Cleaning the `host_name` Column

In [ ]:
df['host_name'] = df['host_name'].fillna('No Host Name')

In [ ]:
df[df['host_name']=='No Host Name'].shape[0]

21

In [ ]:
df['host_name'].isnull().sum()

np.int64(0)

## 3. Cleaning the `neighbourhood_group` Column

In [ ]:
df['neighbourhood_group'] = df['neighbourhood_group'].astype('category')

In [ ]:
df['neighbourhood_group'].dtype

CategoricalDtype(categories=['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island'], ordered=False, categories_dtype=object)

## 4. Cleaning the `neighbourhood` Column

In [ ]:
df['neighbourhood'] = df['neighbourhood'].astype('category')

In [ ]:
df['neighbourhood'].dtype

CategoricalDtype(categories=['Allerton', 'Arden Heights', 'Arrochar', 'Arverne',
                  'Astoria', 'Bath Beach', 'Battery Park City', 'Bay Ridge',
                  'Bay Terrace', 'Bay Terrace, Staten Island',
                  ...
                  'Westerleigh', 'Whitestone', 'Williamsbridge',
                  'Williamsburg', 'Willowbrook', 'Windsor Terrace',
                  'Woodhaven', 'Woodlawn', 'Woodrow', 'Woodside'],
, ordered=False, categories_dtype=object)

In [ ]:
df['neighbourhood'].nunique()

221

## 5. Cleaning the `room_type` Column

In [ ]:
df['room_type'] = df['room_type'].astype('category')

In [ ]:
df['room_type'].dtype

CategoricalDtype(categories=['Entire home/apt', 'Private room', 'Shared room'], ordered=False, categories_dtype=object)

In [ ]:
df['room_type'].nunique()

3

## 6. Cleaning the `last_review` Column

In [ ]:
df['last_review'] = pd.to_datetime(df['last_review'])

In [ ]:
df['last_review'].dtype

dtype('<M8[ns]')

## 7. Cleaning the `price` Column

In [ ]:
df.drop(df[df['price']==0].index, inplace=True)

In [ ]:
df.shape

(48884, 16)

In [ ]:
df[df['price'] == 0].shape[0]

0

In [ ]:
df[df['price'] < 0].shape[0]

0

## 8. Cleaning the `minimum_nights` Column

In [ ]:
df['minimum_nights']

0         1
1         1
2         3
3         1
4        10
         ..
48890     2
48891     4
48892    10
48893     1
48894     7
Name: minimum_nights, Length: 48884, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48884 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48884 non-null  int64
 1   name                            48884 non-null  object
 2   host_id                         48884 non-null  int64
 3   host_name                       48884 non-null  object
 4   neighbourhood_group             48884 non-null  category
 5   neighbourhood                   48884 non-null  category
 6   latitude                        48884 non-null  float64
 7   longitude                       48884 non-null  float64
 8   room_type                       48884 non-null  category
 9   price                           48884 non-null  int64
 10  minimum_nights                  48884 non-null  int64
 11  number_of_reviews               48884 non-null  int64
 12  last_review                     38833 non-null  datetime64[ns]
 13  reviews_per_month               38833 non-null  float64
 14  calculated_host_listings_count  48884 non-null  int64
 15  availability_365                48884 non-null  int64
dtypes: category(3), datetime64[ns](1), float64(3), int64(7), object(2)
memory usage: 5.4+ MB

In [ ]:
df.isnull().sum()

id                                    0
name                                  0
host_id                               0
host_name                             0
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10051
reviews_per_month                 10051
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [ ]:
df.describe(include='all')

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
count,4.888400e+04,48884,4.888400e+04,48884,48884,48884,48884.000000,48884.000000,48884,48884.000000,48884.000000,48884.000000,38833,38833.000000,48884.000000,48884.000000
unique,NaN,47895,NaN,11451,5,221,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Hillside Hotel,NaN,Michael,Manhattan,Williamsburg,NaN,NaN,Entire home/apt,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,18,NaN,417,21660,3919,NaN,NaN,25407,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1.901679e+07,NaN,6.762203e+07,NaN,NaN,NaN,40.728953,-73.952176,NaN,152.755053,7.029887,23.271991,2018-10-04 01:15:09.896222208,1.373128,7.144628,112.779498
min,2.539000e+03,NaN,2.438000e+03,NaN,NaN,NaN,40.499790,-74.244420,NaN,10.000000,1.000000,0.000000,2011-03-28 00:00:00,0.010000,1.000000,0.000000
25%,9.470548e+06,NaN,7.817310e+06,NaN,NaN,NaN,40.690100,-73.983080,NaN,69.000000,1.000000,1.000000,2018-07-08 00:00:00,0.190000,1.000000,0.000000
50%,1.967574e+07,NaN,3.079257e+07,NaN,NaN,NaN,40.723080,-73.955685,NaN,106.000000,3.000000,5.000000,2019-05-19 00:00:00,0.720000,1.000000,45.000000
75%,2.915297e+07,NaN,1.074344e+08,NaN,NaN,NaN,40.763120,-73.936290,NaN,175.000000,5.000000,24.000000,2019-06-23 00:00:00,2.020000,2.000000,227.000000
max,3.648724e+07,NaN,2.743213e+08,NaN,NaN,NaN,40.913060,-73.712990,NaN,10000.000000,1250.000000,629.000000,2019-07-08 00:00:00,58.500000,327.000000,365.000000
std,1.098432e+07,NaN,7.861666e+07,NaN,NaN,NaN,0.054532,0.046159,NaN,240.170260,20.512224,44.551331,NaN,1.680391,32.956185,131.627271

In [ ]:
df.to_csv('airbnb_cleaned.csv', index=False)

## Cleaning Summary

The dataset has been successfully cleaned and prepared for exploratory data analysis. Missing values were handled appropriately, categorical variables were converted to the correct data types, invalid price records were removed, and date fields were converted into datetime format. The cleaned dataset is now ready for visualization and business analysis.